import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
from typing import List
from app.db.models import Article
from jinja2 import Template

class EmailService:
    def __init__(self):
        self.sender_email = os.getenv("EMAIL_SENDER")
        self.password = os.getenv("EMAIL_PASSWORD")
        self.recipient_email = os.getenv("EMAIL_RECIPIENT")
        self.smtp_server = "smtp.gmail.com"
        self.smtp_port = 587

    def send_daily_digest(self, articles: List[Article]):
        if not articles:
            print("No articles to email.")
            return

        if not self.sender_email or not self.password:
            print("❌ Email credentials not set. Skipping email.")
            return

        print(f"📧 Preparing email with {len(articles)} articles...")
        
        # 1. Create the email content
        subject = f"Your Daily AI News Digest ({len(articles)} Articles)"
        html_content = self._generate_html(articles)

        # 2. Setup the MIME
        msg = MIMEMultipart()
        msg['From'] = self.sender_email
        msg['To'] = self.recipient_email
        msg['Subject'] = subject
        msg.attach(MIMEText(html_content, 'html'))

        # 3. Send via SMTP
        try:
            server = smtplib.SMTP(self.smtp_server, self.smtp_port)
            server.starttls() # Secure the connection
            server.login(self.sender_email, self.password)
            server.send_message(msg)
            server.quit()
            print("✅ Email sent successfully!")
        except Exception as e:
            print(f"❌ Failed to send email: {e}")

    def _generate_html(self, articles: List[Article]) -> str:
        # Simple HTML Template
        template_str = """
        <html>
        <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h1 style="color: #2c3e50;">🤖 Daily AI News</h1>
            <p>Here are the top stories for today:</p>
            <hr>
            {% for article in articles %}
            <div style="margin-bottom: 20px; padding: 15px; border: 1px solid #eee; border-radius: 5px;">
                <h3 style="margin-top: 0;"><a href="{{ article.url }}" style="color: #3498db; text-decoration: none;">{{ article.title }}</a></h3>
                <p style="color: #666; font-size: 0.9em;">Source: {{ article.source }} | Score: <strong>{{ article.relevance_score }}/10</strong></p>
                <p style="line-height: 1.5;">{{ article.summary }}</p>
            </div>
            {% endfor %}
            <hr>
            <p style="font-size: 0.8em; color: #999; text-align: center;">Generated by your AI News Aggregator</p>
        </body>
        </html>
        """
        template = Template(template_str)
        return template.render(articles=articles)
