from app.services.email_service import EmailService
from app.db.models import Article
from dotenv import load_dotenv
import datetime

load_dotenv()

def main():
    print("📧 Initializing Email Service...")
    email_service = EmailService()
    
    # Create dummy articles for testing
    dummy_articles = [
        Article(
            title="Test Article 1: AI is Amazing",
            url="https://example.com/ai-amazing",
            source="Test Source",
            summary="This is a test summary generated by the test script.",
            relevance_score=9,
            created_at=datetime.datetime.now()
        ),
        Article(
            title="Test Article 2: Python is Cool",
            url="https://example.com/python-cool",
            source="Test Source",
            summary="Another test summary to check the HTML formatting.",
            relevance_score=8,
            created_at=datetime.datetime.now()
        )
    ]
    
    print("🚀 Sending Test Email...")
    email_service.send_daily_digest(dummy_articles)

if __name__ == "__main__":
    main()
